Repository JEONG-J/AppleAcademyChange4_Konglish, pull requests merged in 2025-07, with the labels that each got.

#20 ✨ [Feat] SwiftData 모델 파일 추가
  Konglish/Konglish/Resources/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  Konglish/Konglish/Resources/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  Konglish/Konglish/Resources/Assets/Assets.xcassets/Contents.json
  Konglish/Konglish/Sources/Model/Domain/CardModel.swift
  Konglish/Konglish/Sources/Model/Domain/CategoryModel.swift
  Konglish/Konglish/Sources/Model/Domain/GameSessionModel.swift
  Konglish/Konglish/Sources/Model/Domain/LevelModel.swift
  Konglish/Konglish/Sources/Presentation/ContentView.swift
Labels: :star: Important

#22 ✨ [Feat] 의존성 추가
  Konglish/Dependency/Sources/DIContainer.swift
  Konglish/Dependency/Sources/EnvironmentValues+Injection.swift
  Konglish/Dependency/Sources/Navigation/NavigationRoute.swift
  Konglish/Dependency/Sources/Navigation/NavigationRouter.swift
  Konglish/Konglish/Sources/Model/Domain/CategoryModel.swift
  Konglish/Konglish/Sources/Model/Domain/GameSessionModel.swift
  Konglish/Konglish/Sources/Model/Domain/UsedCardModel.swift
Labels: :hammer: Refactor, :star: Important

#28 ✨ [Feat] Aim을 맞춰서 카드 오브젝트 찾기
  Konglish/ARCore/Sources/Features/CardDetector.swift
Labels: :sparkles: Feature

#29 📝 [Docs] README.md 팀원 추가
  README.md
Labels: :page_facing_up: Docs

#32 ✨ [Feat] 라이프 카운트, 스코어 관리, 단어 제출 구현
  Konglish/ARCore/Sources/Common/ARCoreError.swift
  Konglish/ARCore/Sources/Data/GameCard.swift
  Konglish/ARCore/Sources/UIComponents/ARContainer.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController+Score.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewControllerDelegate.swift
Labels: :sparkles: Feature

#33 ✨ [Feat] CardRotator - AR 카드를 양방향 뒤집는 기능
  Konglish/ARCore/Sources/Entities/CardEntity.swift
  Konglish/ARCore/Sources/Features/CardDetector.swift
  Konglish/ARCore/Sources/Features/CardRotator.swift
Labels: :sparkles: Feature

#40 ✨ [Feat] 카드 뒤집기 기능 구현
  Konglish/ARCore/Sources/Entities/CardEntity.swift
  Konglish/ARCore/Sources/Features/CardDetector.swift
  Konglish/ARCore/Sources/UIComponents/ARContainer.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController+ARSetup.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController+CardFlipper.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController.swift
Labels: :sparkles: Feature

#41 ✨ [Feat] CardEntity 호버링
  Konglish/ARCore/Sources/Components/CardComponent.swift
  Konglish/ARCore/Sources/Components/DynamicTextureComponent.swift
  Konglish/ARCore/Sources/Entities/CardEntity.swift
  Konglish/ARCore/Sources/System/DynamicTextureSystem.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController+ARSetup.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController.swift
Labels: :sparkles: Feature

#46 ✨ [Feat] 점수 계산 기획 변경 대응
  Konglish/ARCore/Sources/Data/GameCard.swift
  Konglish/ARCore/Sources/UIComponents/ARContainer.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController+Score.swift
Labels: :sparkles: Feature

#54 💄 [Design] 카드 엔티티 교체, 카드 엔티티에 조명 추가
  Konglish/ARCore/Packages/KonglishARProject/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Konglish/ARCore/Packages/KonglishARProject/Sources/KonglishARProject/KonglishARProject.rkassets/CardV2.2.usdz
  Konglish/ARCore/Packages/KonglishARProject/Sources/KonglishARProject/KonglishARProject.rkassets/Scene.usda
Labels: :lipstick: UI

#55 ✨ [Feat] DynamicCardContentSystem 개선
  Konglish/ARCore/Sources/Components/CardComponent.swift
  Konglish/ARCore/Sources/Features/AR/ARFeatureProvider.swift
  Konglish/ARCore/Sources/Features/AR/CardDetector.swift
  Konglish/ARCore/Sources/Features/AR/CardPositioner.swift
  Konglish/ARCore/Sources/Features/AR/CardRotator.swift
  Konglish/ARCore/Sources/Features/AR/PlaneVisualizer.swift
  Konglish/ARCore/Sources/Features/DynamicTexture/CardContentImageCache.swift
  Konglish/ARCore/Sources/Features/DynamicTexture/CardContentImageProvider.swift
  Konglish/ARCore/Sources/Features/DynamicTexture/CardContentImageReader.swift
  Konglish/ARCore/Sources/Features/DynamicTexture/CardContentImageWriter.swift
  Konglish/ARCore/Sources/System/DynamicCardContentSystem.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController+ARSetup.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController.swift
Labels: :sparkles: Feature

#62 ✨ [Feat] 가이딩 뷰 기능
  Konglish/ARCore/Sources/Features/AR/CardRotator.swift
  Konglish/ARCore/Sources/System/DynamicCardContentSystem.swift
  Konglish/Dependency/Sources/DIContainer.swift
  Konglish/Dependency/Sources/Navigation/NavigationRoute.swift
  Konglish/Konglish/Sources/Common/DesignSystem/Color.swift
  Konglish/Konglish/Sources/KonglishApp.swift
  Konglish/Konglish/Sources/Presentation/Appflow/ViewModels/GuidingViewModel.swift
  Konglish/Konglish/Sources/Presentation/Appflow/Views/GuidingView.swift
  Konglish/Konglish/Sources/Presentation/Appflow/Views/SwipeTabView.swift
  Konglish/Konglish/Sources/Presentation/ContentView.swift
  Konglish/Konglish/Sources/Presentation/Navi/NavigationRoutingView.swift
Labels: :lipstick: UI, :sparkles: Feature

#63 ✨[Feat] Konglish 모듈 메인 앱에 ARCore 기능 연계
  Konglish/Konglish/Sources/Model/Domain/GameModelMapper.swift
  Konglish/Konglish/Sources/Presentation/AR/ViewModels/ARViewModel.swift
  Konglish/Konglish/Sources/Presentation/AR/Views/ARView.swift
  Konglish/Konglish/Sources/Presentation/Overlay/Views/CheckScanOverlay.swift
  Konglish/Konglish/Sources/Presentation/Overlay/Views/FinishedOverlay.swift
  Konglish/Konglish/Sources/Presentation/Overlay/Views/OnShowingCardOverlay.swift
  Konglish/Konglish/Sources/Presentation/Overlay/Views/PlayingGameOverlay.swift
  Konglish/Konglish/Sources/Presentation/Overlay/Views/StartOverlay.swift
Labels: :sparkles: Feature

#65 🐛 [Fix] 평면 스캔 효율성 해결, currentDetectedPlane 갯수 오류 해결
  ARCoreDemoApp/ARCoreDemoApp/Sources/ContentView.swift
  Konglish/ARCore/Project.swift
  Konglish/ARCore/Sources/Features/AR/CardPositioner.swift
  Konglish/ARCore/Sources/Features/DynamicTexture/CardContentImageProvider.swift
  Konglish/ARCore/Sources/UIComponents/ARContainer.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController+ARSetup.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewController+PlaneDetection.swift
  Konglish/ARCore/Sources/UIComponents/ARContainerViewControllerDelegate.swift
Labels: :bug: BugFix

#70 ✨ [Feat] AR 오버레이 작업
  Konglish/Dependency/Sources/Navigation/NavigationRoute.swift
  Konglish/Konglish/Resources/Assets/Assets.xcassets/AR/totalCard.imageset/Contents.json
  Konglish/Konglish/Resources/Assets/Assets.xcassets/AR/totalCard.imageset/totalCard.pdf
  Konglish/Konglish/Resources/Assets/Assets.xcassets/ButtonIcon/targetBtn.imageset/Contents.json
  Konglish/Konglish/Resources/Assets/Assets.xcassets/ButtonIcon/targetBtn.imageset/targetBtn.pdf
  Konglish/Konglish/Sources/Common/Enum/Button/IconButtonType.swift
  Konglish/Konglish/Sources/Common/UIComponents/AR/GameStatus.swift
  Konglish/Konglish/Sources/KonglishApp.swift
  Konglish/Konglish/Sources/Presentation/AR/ViewModels/DetailCardViewModel.swift
  Konglish/Konglish/Sources/Presentation/AR/Views/ARView.swift
  Konglish/Konglish/Sources/Presentation/Category/Views/CategorySelectView.swift
  Konglish/Konglish/Sources/Presentation/Level/Views/LevelView.swift
  Konglish/Konglish/Sources/Presentation/Navi/NavigationRoutingView.swift
  Konglish/Konglish/Sources/Presentation/Overlay/Views/OnShowingCardOverlay.swift
  Konglish/Konglish/Sources/Presentation/Overlay/Views/PlayingGameOverlay.swift
  Konglish/Konglish/Sources/Presentation/Overlay/Views/StartOverlay.swift
Labels: :sparkles: Feature
